{
 "title": "RTMP2HLS",
 "time": { "from": "now-7m", "to": "now" },
 "panels": [
  {
   "title": "Active streams",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_streams", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Object store uploads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "targets": [
    { "expr": "rate(object_store_uploads[1m])", "legendFormat": "Object store upload rate" }
   ]
  },
  {
   "title": "RTMP ingress rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(video_ingress_bytes[1m])", "legendFormat": "Video ingress rate (B)" },
    { "expr": "rate(audio_ingress_bytes[1m])", "legendFormat": "Audio ingress rate (B)" }
   ]
  }
 ]
}